# Basic linstor configuration toml file
# For more options check documentation https://www.linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor-external-database

[db]
# user = "linstor"
# password = "linstor"

connection_url = "{{ linstor_db_connection_url }}"

## if you want to use TLS, only since LINSTOR 1.2.1
{% if linstor_db_ca_certificate | d('') | length %}
ca_certificate = "{{ linstor_db_ca_certificate }}"
{% endif %}

{% if linstor_db_client_certificate | d('') | length %}
client_certificate = "{{ linstor_db_client_certificate }}"
{% endif %}

## if you want to use client TLS authentication too, only since LINSTOR 1.2.1
{% if linstor_db_key | d('') | length %}
client_key_pkcs8_pem = "{{ linstor_db_key }}"
{% endif %}
## set client_key_password if private key has a password
{% if linstor_db_secret | d('') | length %}
client_key_password = "{{ linstor_db_secret }}"
{% endif %}
