- set_fact:
    _etcd_local_env: "{{ temp_directory }}/{{ ansible_host }}/etcd.env"

- fetch:
    src: "{{ etcd_env_file }}"
    dest: "{{ temp_directory }}/{{ ansible_host }}/"
    flat: yes

- set_fact:
    linstor_db_connection_url: "etcd://{{ lookup('ini', 'ETCD_INITIAL_CLUSTER type=properties file='~_etcd_local_env) | regex_replace('etcd.+?=https?:\/\/', '') | join('') }}"
  when: linstor_db_connection_url is not defined

- set_fact:
    etcd_ca_certificate: "{{ lookup('ini', 'ETCD_TRUSTED_CA_FILE type=properties file='~_etcd_local_env) }}"
  when: etcd_ca_certificate is not defined

- set_fact:
    etcd_client_certificate: "{{ lookup('ini', 'ETCD_CERT_FILE type=properties file='~_etcd_local_env) }}"
  when: etcd_client_certificate is not defined

- set_fact:
    linstor_db_key: "{{ lookup('ini', 'ETCD_KEY_FILE type=properties file='~_etcd_local_env) }}"
  when: linstor_db_key is not defined
