---
- name: Uninstall binary packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop: "{{ os_packages[ansible_distribution|lower] }}"
  tags:
  - never
  - uninstall

- tags: install
  block:
  - name: Add linbit ppa
    apt_repository:
      repo: "ppa:linbit/linbit-drbd9-stack"

  - name: Update APT package cache
    apt:
      update_cache: true

  ## To get specific versions: apt-cache search linstor* | awk '{print $1}' | xargs apt-cache madison
  - name: Install os packages
    apt:
      name: "{{ item }}"
    loop: "{{ os_packages[ansible_distribution|lower] }}"

  - name: Check if firewall is running
    shell: systemctl status ufw
    register: firewall
    failed_when: ( firewall.rc not in [ 0, 3, 4 ] )

  - name: Allow linstor ports
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
    - 3366
    - 3370
    - 3376
    - 7000:8000
    when: firewall.rc == 0
