- tags: always
  block:
  - name: Install ansible requirements
    pip:
      executable: pip3
      extra_args: -U
      name: "{{ item }}"
    loop: "{{ lookup('file', 'requirements.txt').splitlines() }}"
    tags: always


## Software installation
- tags: install
  block:
  - include_tasks: "install-{{ ansible_distribution|lower }}.yml"

  - name: Enable and start Linstor Controller
    systemd:
      name: linstor-controller.service
      daemon_reload: yes
      state: restarted
      enabled: yes

  - name: Enable and start Linstor Satellite
    systemd:
      name: linstor-satellite.service
      daemon_reload: yes
      state: restarted
      enabled: yes

  - name: Setup linstor-client.conf
    template:
      src: linstor-client.j2
      dest: /etc/linstor/linstor-client.conf

  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30

  - name: Initialize the Linstor control node as pure Controller
    shell: linstor node create {{ ansible_nodename }} {{ ansible_all_ipv4_addresses | ipaddr(drbd_replication_network) | first }} --node-type {% if 'linstor_satellites' not in group_names %}Controller{% else %}Combined{% endif %}
    register: linstor_create_result
    failed_when: ( linstor_create_result.rc not in [ 0, 10 ] )

  - debug:
      msg: |
        {{ lookup('pipe', 'linstor node list') }}


- include_tasks: storage-pool.yml
  loop: "{{ linstor_pools }}"
  tags: storage
