- tags: storage
  when: pool.type == 'filethin'
  block:
  - name: Create storage pool directory
    file:
      path: "{{ pool.base_path | d(filethin_base_path) }}/{{ pool.name }}"
      state: directory
      mode: '0755'

  - name: Create the storage pool for {{ pool.name }}
    shell: linstor storage-pool create {{ pool.type }} {{ ansible_nodename }} {{ pool.name }} {{ pool.base_path | d(filethin_base_path) }}/{{ pool.name }}
    register: storage_pool_create_result
    failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )


- tags: storage
  when: pool.type == 'lvmthin'
  block:
  - vars:
      _disks: []
    include_tasks: get-disks.yml
    loop: "{{ pool.physical_disks }}"

  - name: Create volume group for LINSTOR
    lvg:
      vg: "{{ vg_name }}"
      pvs: "{{ _disks | join(',') }}"
    when: _disks | d([]) | length

  - name: Create thin LVM pool on VG {{ vg_name }}
    lvol:
      vg: "{{ vg_name }}"
      thinpool: "{{ pool.name }}"
      size: "{{ pool.size | d('100%FREE') }}"
      opts: -Zn
    ignore_errors: yes

  - name: Create the linstor storage pool
    shell: linstor storage-pool create {{ pool.type }} {{ ansible_nodename }} {{ pool.name }} {{ vg_name }}/{{ pool.name }}
    register: storage_pool_create_result
    failed_when: ( storage_pool_create_result.rc not in [ 0, 10 ] )
